- name: prepare base foundation
  hosts: sonar-nexus
  tasks:
    - name: install tools
      apt:
        name: 
          - openjdk-17-jre-headless
          - net-tools
          - unzip
          - docker.io
      
    
    - name: create a jenkins user 
      ansible.builtin.user:
        name: jenkins
        state: present
        group: docker

 #   - name: get nexus binaries
  #    ansible.builtin.get_url:
   #     url: https://download.sonatype.com/nexus/3/nexus-3.82.0-08-linux-x86_64.tar.gz
    #    path: /opt 
     # register: nexus_download
      
    # - name: unarchive nexus binaries
      #ansible.builtin.unarchive:
       # src: {{nexus_download}}
        #dest: /opt
      #register: unarchived_nexus_directory

