- name: prepare base foundation
  hosts: sonar-nexus
  become: true
  tasks:
    - name: install tools
      apt:
        name: 
          - openjdk-17-jre-headless
          - net-tools
          - unzip
          - docker.io
      
    
    - name: create a jenkins user 
      ansible.builtin.user:
        name: jenkins
        state: present
        group: docker

    - name: run sonraqube container
      ansible.builtin.command: sudo docker run -d -p 9000:9000 sonarqube:lts-community